# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

python:
  install:
    - requirements: requirements/requirements-base.txt
    - requirements: requirements/requirements-doc.txt
