channels:
  - ioam
  - bokeh
  - conda-forge
  - defaults
dependencies:
  - datashader=0.6.5
  - ipywidgets=7.1.0
  - tifffile=0.12.1
  - widgetsnbextension=3.1.0
  - bokeh=0.12.14
  - dask=0.15.4
  - ffmpeg=3.4
  - ipython=6.1.0
  - matplotlib=2.1.2
  - mkl=2018.0.1
  - natsort=5.2.0
  - numpy=1.13.3
  - pandas=0.22.0
  - plotly=2.4.1
  - scikit-image=0.13.1
  - scipy=1.0.0
  - seaborn=0.8.1
  - xarray=0.10.0
  - holoviews=1.9.5
  - param=1.5.1
  - paramnb=2.0.2
  - pip:
    - dash==0.20.0
    - dash-core-components==0.18.1
    - dash-html-components==0.8.0
    - dash-renderer==0.11.3
    - opencv-contrib-python==3.3.0.10
    - sk-video==1.1.8

